### ISSUE TITLE
Accomodate for daylight saving time

### ISSUE THREAD

**Issue by Ashlynn223** [insightorchards/calendar-service#90]
Business Context
We want time for recurring events to stay consistent when date crosses over into DST.

Notes: getMillisecondsBetween function may need modification in how it's used. 

Acceptance Criteria
Given I create a recurring event that spans into DST transition
When I see the recurring events after DST
Then the date time stays the same is what it was originally created with

**Comment by elliedori** [comment]
See https://stackoverflow.com/questions/38771638/how-to-specify-an-rrule-taking-into-account-daylight-savings-time

**Comment by elliedori** [comment]
See also https://stackoverflow.com/questions/73409598/rrule-js-recurrence-series-changes-time-of-day-in-time-zone-after-daylight-sav
